
development:
  adapter: postgresql
  encoding: utf8
  database: new_cms_development
  pool: 5
  username: nedpike
  password: secretpassword

test:
  adapter: postgresql
  encoding: utf8
  database: new_cms_test
  pool: 5
  username: nedpike
  password: secretpassword

production:
  adapter: postgresql
  encoding: utf8
  database: new_cms_test
  pool: 5
  username: nedpike
  password: secretpassword

